///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "A3E45300-3B12-4243-AD1D-7CB867F9FAF2"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (passive_electrical_circuits)"
#define COCLASS_UUID "663A3D7A-F747-4980-960F-20F21C65551B"
#define COCLASS_NAME "MGA Interpreter CoClass (passive_electrical_circuits)"
#define COCLASS_PROGID "MGA.Interpreter.passive_electrical_circuits"

#define COCLASS_UUID_EXPLODED1  0x663a3d7a
#define COCLASS_UUID_EXPLODED2   0xf747
#define COCLASS_UUID_EXPLODED3   0x4980
#define COCLASS_UUID_EXPLODED4   0x96
#define COCLASS_UUID_EXPLODED5   0xf
#define COCLASS_UUID_EXPLODED6   0x20
#define COCLASS_UUID_EXPLODED7   0xf2
#define COCLASS_UUID_EXPLODED8   0x1c
#define COCLASS_UUID_EXPLODED9   0x65
#define COCLASS_UUID_EXPLODED10  0x55
#define COCLASS_UUID_EXPLODED11  0x1b


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "passive_electrical_circuits"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "passive_electrical_circuits Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "passive_electrical_circuits"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
